# ---------------------------------------------------------------
# Kubernetes Ingress – generated by Terraform (do not edit manually)
# Apply AFTER terraform apply completes and the LBC is running:
#   kubectl apply -f k8s/ingress.yaml
# ---------------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-boutique
  namespace: ${app_namespace}
  annotations:
    # Use AWS Load Balancer Controller
    kubernetes.io/ingress.class: alb

    # Internet-facing ALB in public subnets
    alb.ingress.kubernetes.io/scheme: internet-facing

    # REQUIRED for Fargate – target pods by IP, not NodePort
    alb.ingress.kubernetes.io/target-type: ip

    # ACM certificate for HTTPS on the ALB (eu-west-1)
    alb.ingress.kubernetes.io/certificate-arn: ${alb_certificate_arn}

    # Expose HTTP (80) and HTTPS (443), redirect HTTP → HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"

    # WAF WebACL – LBC associates it to the ALB automatically
    alb.ingress.kubernetes.io/wafv2-acl-arn: ${waf_acl_arn}

    # Health check – matches frontend readiness/liveness probe path
    alb.ingress.kubernetes.io/healthcheck-path: ${health_check_path}
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: "8080"
    alb.ingress.kubernetes.io/success-codes: "200"

    # Deregistration delay – how long ALB waits before removing a pod
    # (keep low for demo, default is 300s)
    alb.ingress.kubernetes.io/deregistration-delay.timeout-seconds: "30"

spec:
  rules:
    - host: ${www_domain}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${app_service_name}
                port:
                  number: ${app_service_port}
